#!/bin/sh

case $1 in
	run) rlwrap sbcl --eval "(asdf:load-system :fe2)" --eval "(defun reload () (asdf:load-system :fe2) (fe2-entry:main))" --eval "(fe2-entry:main)" ;;
	image) sbcl --eval "(asdf:make :fe2/image)" ;;
	build) sbcl --eval "(asdf:make :fe2/release)" ;;
	*) echo "Usage: $0 <run|image|build>"; exit 1
esac
