[Graphics]
width = 1280
height = 720
fullscreen = "none"
borders = true
vsync = true
wireframe = false
msaa = 2
fov = 90
physics_fps = 60
monitor_index = 0

[Sound]
master_volume = 0
music_volume = 100
effect_volume = 100
